name: ADA Compliance Check and Fix

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'force-app/main/default/lwc/**'
      - 'force-app/main/default/aura/**'
      - 'force-app/main/default/components/**'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  ada-compliance:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check for package.json and install dependencies
        run: |
          if [ -f "package.json" ]; then
            echo "Found package.json, installing project dependencies..."
            npm install
          else
            echo "No package.json found, skipping project dependencies..."
          fi

      - name: Get changed files
        id: changed-files
        run: |
          # Get list of changed files in the PR
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep -E '\.(js|ts|html|css)$' | grep -E '(lwc|aura|components)/' || true)
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "Changed files: $CHANGED_FILES"

      - name: Run ADA Compliance Check and Fix
        if: steps.changed-files.outputs.changed_files != ''
        run: |
          chmod +x .github/scripts/ada-compliance-fix.sh
          .github/scripts/ada-compliance-fix.sh "${{ steps.changed-files.outputs.changed_files }}"

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit ADA fixes
        if: steps.verify-changed-files.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "🔧 Auto-fix ADA compliance issues

          - Applied accessibility improvements using GitHub Copilot CLI
          - Fixed ARIA attributes, alt text, keyboard navigation, and color contrast
          - Ensured WCAG 2.1 AA compliance standards"

      - name: Push changes
        if: steps.verify-changed-files.outputs.changes == 'true'
        run: |
          git push origin HEAD:${{ github.head_ref }}

      - name: Comment on PR
        if: steps.verify-changed-files.outputs.changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **ADA Compliance Auto-Fix Applied**\n\nGitHub Copilot CLI has automatically scanned and fixed accessibility issues in your Salesforce components:\n\n✅ ARIA attributes optimized\n✅ Alt text for images added/improved\n✅ Keyboard navigation enhanced\n✅ Color contrast issues addressed\n✅ Screen reader compatibility improved\n\nPlease review the changes and test the accessibility improvements.'
            })

      - name: Create ADA compliance report
        if: always()
        run: |
          echo "# ADA Compliance Report" > ada-report.md
          echo "Generated on: $(date)" >> ada-report.md
          echo "" >> ada-report.md
          echo "## Files Scanned" >> ada-report.md
          echo "${{ steps.changed-files.outputs.changed_files }}" >> ada-report.md
          echo "" >> ada-report.md
          echo "## Status" >> ada-report.md
          if [ "${{ steps.verify-changed-files.outputs.changes }}" == "true" ]; then
            echo "✅ ADA fixes applied automatically" >> ada-report.md
          else
            echo "✅ No ADA issues found or all files already compliant" >> ada-report.md
          fi

      - name: Upload ADA report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ada-compliance-report
          path: ada-report.md